### ISSUE TITLE
composer.json missing

### ISSUE THREAD

**Issue by kludikovsky** [w010/w_query2csv#5]
I am missing the composer.json file, and therefore (not tested yet) the possibility to install the extension via composer.
How can I install this extension sing composer? 

Or what is the alternative way to get the extension installed?

I am just starting with composer, so please bear with me.)

**Comment by w010** [comment]
Hello, since I don't use composer I never added its config. You can do one of these:
- install the ext in classic way by Extension Manager, or
- try the version 0.6.2-dev I just commited to _dev_ branch: https://github.com/w010/w_query2csv/tree/dev
I added the composer.json, please check if it works now with composer.

**Comment by w010** [comment]
@kludikovsky Did that fix your problem? Does the composer work now for you so we can merge this and close the issue?
